use cob_credito
go

if exists (select 1 from sysobjects where name = 'sp_crea_op_redes')
   drop proc sp_crea_op_redes 
go

create proc sp_crea_op_redes
        @s_date                       datetime = null,
        @s_ssn                        int = null,
        @s_sesn                       int = null,
        @s_ofi                        smallint = null,
        @s_user                       login = null,
        @s_term                       varchar(30) = null,
        @s_srv                        varchar(30) = null,
        @t_debug                      char(1) = 'N',
        @t_file                       varchar(14) = null,
        @t_from                       varchar(20) = null,
        @i_fecha_proceso              datetime = null,
        @i_usuario_tr                 login = null,
        @i_tramite_activa             int = null,
        @i_tramite                    int = null,       --Archivo Redescuento
        @i_modo                       smallint = null   --Archivo Redescuento 1 Crea,  null
as

DECLARE @w_sp_name    		      varchar(64),
	@w_nombre_completo            varchar(64),
        @w_error                      int,
        @w_return                     int,
        @w_ente                       int,
        @w_ente_empresa               int,
        @w_subtipo                    char(30),
        @w_identificacion             numero,
        @w_linea_credito              catalogo,
        @w_norma_legal                catalogo,
        @w_dir_predio                 varchar(60),
        @w_dir_cli                    varchar(60),
        @w_monto                      money,
        @w_moneda                     tinyint,
        @w_cod_entidad                char(3),
        @w_sector                     catalogo,
        @w_oficina_oper               smallint,
        @w_oficial                    smallint,
        @w_destino                    catalogo,
        @w_ubicacion                  int,
        @w_fecha_inicio               datetime,
        @w_forma_pago                 catalogo,
        @w_referencia_desem           cuenta,
        @w_estado_registro            char(1),
        @w_banco                      cuenta,
        @w_ciudad                     int,
        @w_periodo                    catalogo,
        @w_num_periodos               smallint,
        @w_clase                      catalogo,
        @w_tramite                    int,
	@w_cupo_linea                 cuenta,
	@w_operacionca                int,
	@w_operacioncai               int,
        @w_operacion                  int,
        @w_descripcion                varchar(255),
        @w_banca                      catalogo,
        @w_var_linea                  varchar(20),
        @w_op_operacion               int,
        @w_concepto_credito           catalogo,
        @w_margen_redescuento         float,
        @w_clase_cartera              catalogo,
        @w_mercado_objetivo           catalogo,
        @w_tipo_productor             varchar(24),
        @w_fecha_redes                datetime,
        @w_valor_proyecto             money,
        @w_sindicado                  char(1),
        @w_asociativo                 char(1),
        @w_incentivo                  char(1),
        @w_pos                        smallint,
        @w_parametro                  varchar(30),
        @w_parametro_of_pag           int,
        @w_parametro_nom_pag          varchar(30),
        @w_parametro_dir              varchar(30),
        @w_par_cod_ase                varchar(30),
        @w_par_cod_pol                varchar(30),
        @w_par_cob_pol                varchar(30),
        @w_par_fec_vig                varchar(30),
        @w_par_cod_alm                varchar(30),
        @w_par_nom_alm                varchar(30),
        @w_par_dir_alm                varchar(30),
        @w_num_pagare                 varchar(24),
        @w_rubro_economico            catalogo,
        @w_op_destino                 catalogo,
        @w_ciudad_inversion           int,
        @w_nom_beneficiario           varchar(64),
        @w_codigo_ciiu                catalogo,
        @w_ced_ruc                    varchar(14),
        @w_nom_oficina                varchar(64),
        @w_direccion                  varchar(200),
        @w_capital                    money,
        @w_valor_redescuento          money,
        @w_periodo_gracia             smallint,
        @w_plazo		      smallint,
        @w_fecha_vto_ini	      datetime,
        @w_fecha_vto_1cap	      datetime,
        @w_fecha_vto_fin	      datetime,
        @w_valor_cuota	              money,
        @w_num_dias                   smallint,
        @w_fecha_inicio_tr            datetime,
        @w_elegible                   char(1),
        @w_forward                    char(1),
        @w_tplazo                     catalogo,
        @w_tdividendo                 catalogo,
        @w_periodo_cap                int,
        @w_periodo_int                int,
        @w_dist_gracia                char(1),
        @w_gracia_cap                 int,
        @w_gracia_int                 int,
        @w_dia_fijo                   int,
        @w_evitar_feriados            char(1),
        @w_num_renovacion             int,
        @w_renovacion                 char(1),
        @w_mes_gracia                 tinyint,
        @w_reajustable                char(1),
        @w_dias_clausula              int,
        @w_periodo_crecimiento        smallint,
        @w_tasa_crecimiento           float,
        @w_opcion_cap                 char(1),
        @w_tasa_cap                   float,
        @w_dividendo_cap              smallint,
        @w_tipo_crecimiento           char(1),
	@w_reestructuracion           char(1),
      	@w_mora_retroactiva           char(1),
        @w_llave_redes                cuenta,
        @w_llave_redes_fin            cuenta,
        @w_subtipo_cliente            catalogo,
        @w_tipo_amortizacion          varchar(60),
        @w_tipo_plan                  char(2),
        @w_de_ced_ruc                 varchar(14),
        @w_ide_ben_1                  varchar(14),
        @w_doc_ben_1                  char(1),
        @w_tipo_ide 	              catalogo,
	@w_nom_ben_1                  descripcion,
        @w_nom_deudor                 descripcion,
	@w_tip_ben_1                  char(2),
        @w_tipo_cliente               catalogo,
	@w_sub_ben_1		      char(2),
        @w_act_ben_1                  money,
        @w_total_activos              money,
        @w_dir_ben_1                  varchar(60),
	@w_tel_ben_1                  cuenta,
        @w_telefono                   cuenta,
        @w_ide_ben_2                  varchar(14),
	@w_nom_ben_2                  descripcion,
        @w_doc_ben_2                  char(1),
	@w_tip_ben_2                  char(2),
	@w_sub_ben_2		      char(2),
        @w_act_ben_2                  money,
        @w_dir_ben_2                  descripcion,
	@w_tel_ben_2                  cuenta,
        @w_ide_ben_3                  varchar(14),
	@w_nom_ben_3                  descripcion,
        @w_doc_ben_3                  char(1),
	@w_tip_ben_3                  char(2),
	@w_sub_ben_3		      char(2),
        @w_act_ben_3                  money,
        @w_dir_ben_3                  descripcion,
	@w_tel_ben_3                  cuenta,
        @w_ide_ben_4                  varchar(14),
	@w_nom_ben_4                  descripcion,
        @w_doc_ben_4                  char(1),
	@w_tip_ben_4                  char(2),
	@w_sub_ben_4		      char(2),
        @w_act_ben_4                  money,
        @w_dir_ben_4                  descripcion,
	@w_tel_ben_4                  cuenta,
        @w_contador                   smallint,
        @w_cliente                    int,
        @w_ofi_pagare                 int,
        @w_nom_oficina_pagare         descripcion,
        @w_fecha_vig_poliza           datetime,
        @w_cod_poliza                 varchar(20),
        @w_cob_poliza                 catalogo,
        @w_cod_almacenadora           smallint,
        @w_nom_almacenera           descripcion,
        @w_cant_unidades              int,
        @w_valor_x_unidad             money,
        @w_valor_total                money,
        @w_sist_almacenamiento        catalogo,
        @w_num_cdm                    varchar(20),
        @w_tipo_tenencia              varchar(20),
        @w_cod_mun_almacen            int,
        @w_dir_almacen                descripcion,
        @w_margen_red_gar             float,
        @w_tipo_tasa                  char(1),
        @w_abonos_cap                 int,
        @w_abonos_int                 int,
        @w_porc_cap                   float,
        @w_porc_cap_1                 float,
        @w_porc_cap_2                 float,
        @w_fecha_hasta_cap            datetime,
        @w_puntos_tasa                float,
        @w_cod_aseguradora            varchar(20),
        @w_ac_divf                    int,
   	@w_cuota_desde_1		smallint ,
   	@w_cuota_hasta_1		smallint ,
   	@w_valor_cuota_1		money ,
   	@w_cuota_desde_2		smallint ,
   	@w_cuota_hasta_2		smallint ,
   	@w_valor_cuota_2		money ,
   	@w_cuota_desde_3		smallint ,
   	@w_cuota_hasta_3		smallint ,
   	@w_valor_cuota_3		money ,
   	@w_cuota_desde_4		smallint ,
   	@w_cuota_hasta_4		smallint ,
   	@w_valor_cuota_4		money ,
   	@w_cuota_desde_5		smallint ,
   	@w_cuota_hasta_5		smallint ,
   	@w_valor_cuota_5		money ,
   	@w_cuota_desde_6		smallint ,
   	@w_cuota_hasta_6		smallint ,
   	@w_valor_cuota_6		money ,
   	@w_cuota_desde_7		smallint ,
   	@w_cuota_hasta_7		smallint ,
   	@w_valor_cuota_7		money ,
   	@w_cuota_desde_8		smallint ,
   	@w_cuota_hasta_8		smallint ,
   	@w_valor_cuota_8		money ,
   	@w_cuota_desde_9		smallint ,
   	@w_cuota_hasta_9		smallint ,
   	@w_valor_cuota_9		money ,
   	@w_cuota_desde_10		smallint ,
   	@w_cuota_hasta_10		smallint ,
   	@w_valor_cuota_10		money ,
   	@w_fecha_amor_1		datetime ,
   	@w_valor_amor_1		money ,
   	@w_tipo_amor_1		smallint ,
   	@w_fecha_amor_2		datetime ,
   	@w_valor_amor_2		money ,
   	@w_tipo_amor_2		smallint ,
   	@w_fecha_amor_3		datetime ,
   	@w_valor_amor_3		money ,
   	@w_tipo_amor_3		smallint ,
   	@w_fecha_amor_4		datetime ,
   	@w_valor_amor_4		money ,
   	@w_tipo_amor_4		smallint ,
   	@w_fecha_amor_5		datetime ,
   	@w_valor_amor_5		money ,
   	@w_tipo_amor_5		smallint ,
   	@w_fecha_amor_6		datetime ,
   	@w_valor_amor_6		money ,
   	@w_tipo_amor_6		smallint ,
   	@w_fecha_amor_7		datetime ,
   	@w_valor_amor_7		money ,
   	@w_tipo_amor_7		smallint ,
   	@w_fecha_amor_8		datetime ,
   	@w_valor_amor_8		money ,
   	@w_tipo_amor_8		smallint ,
   	@w_fecha_amor_9		datetime ,
   	@w_valor_amor_9		money ,
   	@w_tipo_amor_9		smallint ,
   	@w_fecha_amor_10		datetime ,
   	@w_valor_amor_10		money ,
   	@w_tipo_amor_10		smallint ,
   	@w_fecha_amor_11		datetime ,
   	@w_valor_amor_11		money ,
   	@w_tipo_amor_11		smallint ,
   	@w_fecha_amor_12		datetime ,
   	@w_valor_amor_12		money ,
   	@w_tipo_amor_12		smallint ,
   	@w_fecha_amor_13		datetime ,
   	@w_valor_amor_13		money ,
   	@w_tipo_amor_13		smallint ,
   	@w_fecha_amor_14		datetime ,
   	@w_valor_amor_14		money ,
   	@w_tipo_amor_14		smallint ,
   	@w_fecha_amor_15		datetime ,
   	@w_valor_amor_15		money ,
   	@w_tipo_amor_15		smallint ,
   	@w_fecha_amor_16		datetime ,
   	@w_valor_amor_16		money ,
   	@w_tipo_amor_16		smallint ,
   	@w_fecha_amor_17		datetime ,
   	@w_valor_amor_17		money ,
   	@w_tipo_amor_17		smallint ,
   	@w_fecha_amor_18		datetime ,
   	@w_valor_amor_18		money ,
   	@w_tipo_amor_18		smallint ,
   	@w_fecha_amor_19		datetime ,
   	@w_valor_amor_19		money ,
   	@w_tipo_amor_19		smallint ,
   	@w_fecha_amor_20		datetime ,
   	@w_valor_amor_20		money ,
   	@w_tipo_amor_20		smallint ,
   	@w_fecha_amor_21		datetime ,
   	@w_valor_amor_21		money ,
   	@w_tipo_amor_21		smallint ,
   	@w_fecha_amor_22		datetime ,
   	@w_valor_amor_22		money ,
   	@w_tipo_amor_22		smallint ,
   	@w_fecha_amor_23		datetime ,
   	@w_valor_amor_23		money ,
   	@w_tipo_amor_23		smallint ,
   	@w_fecha_amor_24		datetime ,
   	@w_valor_amor_24		money ,
   	@w_tipo_amor_24		smallint ,
   	@w_fecha_amor_25		datetime ,
   	@w_valor_amor_25		money ,
   	@w_tipo_amor_25		smallint ,
   	@w_fecha_amor_26		datetime ,
   	@w_valor_amor_26		money ,
   	@w_tipo_amor_26		smallint ,
   	@w_fecha_amor_27		datetime ,
   	@w_valor_amor_27		money ,
   	@w_tipo_amor_27		smallint ,
   	@w_fecha_amor_28		datetime ,
   	@w_valor_amor_28		money ,
   	@w_tipo_amor_28		smallint ,
   	@w_fecha_amor_29		datetime ,
   	@w_valor_amor_29		money ,
   	@w_tipo_amor_29		smallint ,
   	@w_fecha_amor_30		datetime ,
   	@w_valor_amor_30		money ,
   	@w_tipo_amor_30		smallint ,
   	@w_fecha_amor_31		datetime ,
   	@w_valor_amor_31		money ,
   	@w_tipo_amor_31		smallint ,
   	@w_fecha_amor_32		datetime ,
   	@w_valor_amor_32		money ,
   	@w_tipo_amor_32		smallint ,
   	@w_fecha_amor_33		datetime ,
   	@w_valor_amor_33		money ,
   	@w_tipo_amor_33		smallint ,
   	@w_fecha_amor_34		datetime ,
   	@w_valor_amor_34		money ,
   	@w_tipo_amor_34		smallint ,
   	@w_fecha_amor_35		datetime ,
   	@w_valor_amor_35		money ,
   	@w_tipo_amor_35		smallint ,
   	@w_fecha_amor_36		datetime ,
   	@w_valor_amor_36		money ,
   	@w_tipo_amor_36		smallint ,
   	@w_fecha_amor_37		datetime ,
   	@w_valor_amor_37		money ,
   	@w_tipo_amor_37		smallint ,
   	@w_fecha_amor_38		datetime ,
   	@w_valor_amor_38		money ,
   	@w_tipo_amor_38		smallint ,
   	@w_fecha_amor_39		datetime ,
   	@w_valor_amor_39		money ,
   	@w_tipo_amor_39		smallint ,
   	@w_fecha_amor_40		datetime ,
   	@w_valor_amor_40		money ,
   	@w_tipo_amor_40		smallint ,
   	@w_fecha_amor_41		datetime ,
   	@w_valor_amor_41		money ,
   	@w_tipo_amor_41		smallint ,
   	@w_fecha_amor_42		datetime ,
   	@w_valor_amor_42		money ,
   	@w_tipo_amor_42		smallint ,
   	@w_fecha_amor_43		datetime ,
   	@w_valor_amor_43		money ,
   	@w_tipo_amor_43		smallint ,
   	@w_fecha_amor_44		datetime ,
   	@w_valor_amor_44		money ,
   	@w_tipo_amor_44		smallint ,
   	@w_fecha_amor_45		datetime ,
   	@w_valor_amor_45		money ,
   	@w_tipo_amor_45		smallint ,
   	@w_fecha_amor_46		datetime ,
   	@w_valor_amor_46		money ,
   	@w_tipo_amor_46		smallint ,
   	@w_fecha_amor_47		datetime ,
   	@w_valor_amor_47		money ,
   	@w_tipo_amor_47		smallint ,
   	@w_fecha_amor_48		datetime ,
   	@w_valor_amor_48		money ,
   	@w_tipo_amor_48		smallint ,
   	@w_fecha_amor_49		datetime ,
   	@w_valor_amor_49		money ,
   	@w_tipo_amor_49		smallint ,
   	@w_fecha_amor_50		datetime ,
   	@w_valor_amor_50		money ,
   	@w_tipo_amor_50		smallint ,
   	@w_fecha_amor_51		datetime ,
   	@w_valor_amor_51		money ,
   	@w_tipo_amor_51		smallint ,
   	@w_fecha_amor_52		datetime ,
   	@w_valor_amor_52		money ,
   	@w_tipo_amor_52		smallint ,
   	@w_fecha_amor_53		datetime ,
   	@w_valor_amor_53		money ,
   	@w_tipo_amor_53		smallint ,
   	@w_fecha_amor_54		datetime ,
   	@w_valor_amor_54		money ,
   	@w_tipo_amor_54		smallint ,
   	@w_fecha_amor_55		datetime ,
   	@w_valor_amor_55		money ,
   	@w_tipo_amor_55		smallint ,
   	@w_fecha_amor_56		datetime ,
   	@w_valor_amor_56		money ,
   	@w_tipo_amor_56		smallint ,
   	@w_fecha_amor_57		datetime ,
   	@w_valor_amor_57		money ,
   	@w_tipo_amor_57		smallint ,
   	@w_fecha_amor_58		datetime ,
   	@w_valor_amor_58		money ,
   	@w_tipo_amor_58		smallint ,
   	@w_fecha_amor_59		datetime ,
   	@w_valor_amor_59		money ,
   	@w_tipo_amor_59		smallint ,
   	@w_fecha_amor_60		datetime ,
   	@w_valor_amor_60		money ,
   	@w_tipo_amor_60		smallint ,
   	@w_cod_rubro_ppal		char(6)	,
   	@w_cant_unid_finan_ppal	int ,
   	@w_costo_inv_rubro_ppal	money ,
   	@w_valor_fin_rubro_ppal	money ,
   	@w_cod_rubro_2		char(6) ,
   	@w_cant_unid_finan_2	        int ,
   	@w_costo_inv_rubro_2	        money ,
   	@w_valor_fin_rubro_2	        money ,
   	@w_cod_rubro_3		char(6) ,
   	@w_cant_unid_finan_3	        int ,
   	@w_costo_inv_rubro_3	        money ,
   	@w_valor_fin_rubro_3		money ,
   	@w_cod_rubro_4		char(6) ,
   	@w_cant_unid_finan_4		int ,
   	@w_costo_inv_rubro_4		money ,
   	@w_valor_fin_rubro_4		money ,
   	@w_cod_rubro_5		char(6)	,
   	@w_cant_unid_finan_5		int ,
   	@w_costo_inv_rubro_5		money ,
   	@w_valor_fin_rubro_5		money ,
   	@w_concepto                  catalogo,
   	@w_cuota                     money,
   	@w_cuota_ant                 money,
   	@w_interes                   money,
   	@w_dividendo                 smallint,
   	@w_destino_t                 char(6),
   	@w_unidad_t                  int,
   	@w_costo_t                   money,
   	@w_valor_t                   money,
   	@w_rol_t                     char(1),
   	@w_banco_pasiva              cuenta,
   	@w_banco_activa              cuenta,
   	@w_tramite_activa            int,
   	@w_operacion_activa          int,
   	@w_operacion_pasiva          int,
   	@w_tipo_redondeo             int,
   	@w_montop                    money,
   	@w_linea_act                 int,
   	@w_num_deudores              smallint,
   	@w_tipo_gar_aso              catalogo,
   	@w_ac_operacion    		int,
   	@w_ac_div_ini      		int,
   	@w_ac_div_fin      		int,
   	@w_ac_rubro        		catalogo,
   	@w_ac_valor        		money,
   	@w_ac_porcentaje   		float,
   	@w_ac_divf_ini     		int,
   	@w_ac_divf_fin     		int,
   	@w_ac_rubrof       		catalogo,
   	@w_ac_secuencial   		int,
        @w_num_operacion                cuenta,
        @w_num_finagro                  int,
	@w_origen_fondos          catalogo,
        @w_cuenta_div             int,
        @w_div_ini                int,
        @w_cuota_tmp              money,
        @w_fin_datos              int,
        @w_ultimo_reg             char(1),
   	@w_tipo_cuota     	  smallint,
        @w_fecha_amortizacion     datetime,
        @w_signo                  char(1),
        @w_num_res          int,
        @w_tramite_activo   int,
        @w_fecha_corte      datetime,
        @w_codigo_externo   varchar(64),
        @w_cont_ddiv   int,
        @w_dias_div    smallint,
        @w_porcentaje  float,
        @w_ruta_fag    int ,
        @w_etapa_fag   tinyint,
        @w_tipo_esp    varchar(30),
        @w_recfag      varchar(30),
        @w_pid_asig	   int,
        @w_fag         char(1),
        @w_ncofag      int,
        @w_cofag       char(1),
        @w_fact_ben_1  datetime,
        @w_pas_fin     money,
        @w_fpas_fin_1  datetime,
        @w_num_desemb  int,
        @w_tnum_desemb int,
        @w_linea_cupo  int,
        @w_tr_tipo     char(1),
   	@w_linea_credito_pren 	varchar(20),
        @w_tr_num_desemb 	int,
	@w_tr_cod_actividad 	catalogo,
        @w_cont_ddiv1   int,
        @w_dias_div1    smallint,
	@w_retorno_cap		char(1),
	@w_retorno_int		char(1),
	@w_sujcred              catalogo,
        @w_fabrica              catalogo,
        @w_callcenter           catalogo,
        @w_apr_fabrica          catalogo,
        @w_rowcount             int,
        @w_monto_solicitado     money,
        @w_tipo_plazo	        catalogo,
        @w_tipo_cuota_cat       catalogo,
        @w_plazo_tra            smallint,
        @w_cuota_aproximada	    money,
        @w_fuente_recurso	    varchar(10),
        @w_tipo_credito	        char(1),
        @w_migrado	            varchar(16)
        

SELECT @w_sp_name       = 'sp_crea_op_redes',
       @w_ente          = 0,
       @w_ente_empresa  = 0,
       @w_tramite       = 0,
       @i_fecha_proceso = @s_date,
       @w_contador      = 0
select @w_pid_asig = @@spid * 100
 /* Obtener codigo de Banco Asignado por Finagro */
 SELECT @w_cod_entidad = pa_char                  -- Campo 58
 FROM cobis..cl_parametro
 WHERE pa_producto = 'CRE'
   and pa_nemonico = 'BAC'
 set transaction isolation level read uncommitted

 
return 0

   ERROR:
   SELECT @w_descripcion = 'CREACION DE TRAMITES' + ' ' + @w_descripcion

      exec cobis..sp_cerror
           @t_debug = @t_debug,
           @t_file  = @t_file,
           @t_from  = @w_sp_name,
           @i_num   = @w_return,
           @i_msg   = @w_descripcion
      return @w_return



                                                              
                                                                                                                                                                                                                                                             
                                                                                                                                                                                                              
go
